repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Gitleaks
        entry: gitleaks protect --staged --config .gitleaks.toml
        language: system
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
